---
- hosts: all
  become: true
  pre_tasks:
    - name: Update packages
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name: "*"
        state: latest
      when: ansible_os_family == "Debian"

- hosts: proxmox
  become: false
  vars_files:
    - default.config.yml
    - vars/config.yml
  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/vars/config.yml"
        - "{{ playbook_dir }}/{{ lookup('env','USER') }}.yml"
      tags: ['always']
  tasks:
    - import_tasks: tasks/access.yml
    - import_tasks: tasks/proxmox.yml

- hosts:
    - apps
    - pihole
  become: true
  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include playbook configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
        - "{{ playbook_dir }}/{{ lookup('env','USER') }}.yml"
      tags: ['always']
  tasks:
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/proxmox_vm.yml
 
- hosts: apps
  become: true
  tasks:
    - import_tasks: tasks/paperless.yml
    - import_tasks: tasks/homer.yml
    - import_tasks: tasks/uptime_kuma.yml
    - import_tasks: tasks/tandoor.yml
    - import_tasks: tasks/nextcloud.yml
