---
collections:
  - ansible.posix
  - community.docker
  - community.general
  - maxhoesel.smallstep

roles:
  - caddy_ansible.caddy_ansible
  - cloudalchemy.prometheus
  # FIXME Does not support PVE 7
  # - ironicbadger.ansible_role_proxmox_nag_removal
