---

- name: Add non-root user
  ansible.builtin.user:
    name: "{{ username }}"
    comment: Darren Meehan
    password: $6$3DYXZFi4sxn.RIZD$xYpX50gR1kotbnoFi0gQ3auV7VKYl7UE0S72Jlo8WSawZYZoeSmygkOMnXJCJDHBsajWvWHgXzAxED1mjWTHk.
    update_password: always
    create_home: yes

- name: Create sudoers.d files
  ansible.builtin.copy:
    src: sudoers/darren
    dest: /etc/sudoers.d
    owner: root
    group: root
    mode: ug+rwX,o=
    force: yes

- name: Set authorized keys
  ansible.posix.authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ lookup('file', '/Users/darren/.ssh/general.pub') }}"

# FIXME Turn off root ssh
