---

- name: Create directory
  file:
    path: ~/apps/archivebox
    state: directory

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: ~/apps/archivebox/docker-compose.yml

# - name: Initial setup
#   shell:
#   # docker-compose run archivebox init --setup
# - name: Run container

# - name: Setup service
