---
- name: 'Base Image Provisioning'
  hosts: default
  become: true

  tasks:
  # Probably do not need this in Ansible
  # simple example for now
    - name: Update all packages
      package:
        name: '*'
        state: latest

    - name: Set hostname
      ansible.builtin.hostname:
        name: "{{ hostname }}"

    - name: Set authorized keys
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ lookup('file', '/Users/darren/.ssh/general.pub') }}"
