---
# tasks file for rust
# FIXME Only works for Ubuntu

- name: Install dependencies
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ rust_dependancies }}"
  become: yes

- name: Install rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

- name: Install sqlx-cli
  shell: cargo install --locked --version={{ sqlx_version }} sqlx-cli --no-default-features --features postgres

- name: Install cargo-edit
  shell: cargo install cargo-edit


  # curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/uri_module.html
# Needed for zero2prod

# I cloned my repo which was already available online at

# Though I needed to install `sqlx`.

# ```
# cargo install --locked --version=0.5.1 sqlx-cli --no-default-features --features postgres
# ```
