---

- name: install dependencies
  package:
    name: "{{ item }}"
    state: latest
  loop: "{{ rust_dependancies }}"
  become: yes

- name: install rustup
  shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

- name: update
  shell: rustup update

- name: install nightly
  shell: rustup toolchain install nightly

- name: setup cargo on current shell
  shell: source {{ lookup('env','HOME') }}/.cargo/env

# FIXME This doesnt work first time despite above comand working...
- name: install sqlx-cli
  shell: cargo install --locked --version={{ sqlx_cli_version }} sqlx-cli --no-default-features --features postgres

- name: install cargo-edit
  shell: cargo install cargo-edit --force

- name: install wrangler
  shell: cargo install wrangler --force
